{"name": "test_without_bug", "status": "passed", "statusDetails": {"message": "XPASS"}, "start": 1758642466202, "stop": 1758642466202, "uuid": "2fcac627-fcfc-4c57-a106-7aad11111e74", "historyId": "bb33ef2621d46ef1f1d5cda365e5afa3", "testCaseId": "bb33ef2621d46ef1f1d5cda365e5afa3", "fullName": "tests.pytest.test_pytest_xfail#test_without_bug", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(resaon='Баг уже исправлен, но на тесте все еще висит маркировка \"xfail\"')"}, {"name": "parentSuite", "value": "tests.pytest"}, {"name": "suite", "value": "test_pytest_xfail"}, {"name": "host", "value": "McSuit"}, {"name": "thread", "value": "14032-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.pytest.test_pytest_xfail"}]}